name: Automation Script Workflow

on:
  push:
    branches:
      - main

jobs:
  automation-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image (added error handling to check success)
      - name: Build Docker image
        run: |
          docker build -t android-emulator .
          docker images  # This will list the available images to confirm if it's built successfully

      # Step 4: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 5: Install dependencies
      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found!"; exit 1; fi

      # Step 6: Download BB Cloud Phone APK from Google Drive link
      - name: Download BB Cloud Phone APK
        run: |
          curl -L -o BB_Cloud_Phone.apk "https://drive.google.com/uc?id=11YyaD6DmaOMPD1aYZPpdFWQuSPGj5dIZ" || { echo 'Download failed!'; exit 1; }

      # Step 7: Install TempMail APK from GitHub repository
      - name: Download TempMail APK
        run: |
          curl -L -o TempMail.apk "https://github.com/Raider-001Dev/Auto-reffeeal-/raw/main/TempMail.apk" || { echo 'Download failed!'; exit 1; }

      # Step 8: Run automation script
      - name: Run automation script
        run: |
          if [ -f automation_script.py ]; then python automation_script.py; else echo 'Script not found!'; exit 1; fi
