name: Automation Script Workflow

on:
  push:
    branches:
      - main

jobs:
  automation-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Download BB Cloud Phone APK from Google Drive link
      - name: Download BB Cloud Phone APK
        run: |
          curl -L -o BB_Cloud_Phone.apk "https://drive.google.com/uc?id=11YyaD6DmaOMPD1aYZPpdFWQuSPGj5dIZ"

      # Install TempMail APK from GitHub repository
      - name: Download TempMail APK
        run: |
          curl -L -o TempMail.apk "https://github.com/Raider-001Dev/Auto-reffeeal-/raw/main/TempMail.apk"

      - name: Run automation script
        run: |
          python automation_script.py
